Repository Team-OYA/backend, pull requests merged in 2024-02, with the labels that each got.

#1 [FEATURE] spring 초기 세팅
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/refactor-request.md
  .gitignore
  pom.xml
  src/main/java/com/oya/kr/global/config/RootConfig.java
  src/main/java/com/oya/kr/global/config/ServletConfig.java
  src/main/java/com/oya/kr/global/config/WebConfig.java
  src/main/java/com/oya/kr/global/dto/ApplicationResponse.java
  src/main/java/com/oya/kr/global/exception/ApplicationException.java
  src/main/java/com/oya/kr/global/exception/ErrorCode.java
  src/main/java/com/oya/kr/global/exception/GlobalExceptionHandler.java
  src/main/java/com/oya/kr/test/controller/TestController.java
  src/main/java/com/oya/kr/test/exception/ErrorCodeList.java
  src/main/java/com/oya/kr/test/mapper/TimeMapper.java
  src/main/resources/com/oya/kr/test/mapper/TimeMapper.xml
  src/main/resources/log4j.xml
  src/main/resources/log4jdbc.log4j2.properties
  src/test/java/com/oya/kr/config/RootConfigTests.java
  src/test/java/com/oya/kr/test/mapper/TimeMapperTest.java
  src/test/resources/log4j.xml
Labels: 🐥 feat

#2 [FEATURE] 기본 도메인 생성
  src/main/java/com/oya/kr/commutiny/domain/Community.java
  src/main/java/com/oya/kr/commutiny/domain/CommunityAdvertisement.java
  src/main/java/com/oya/kr/commutiny/domain/CommunityReport.java
  src/main/java/com/oya/kr/commutiny/domain/CommunityType.java
  src/main/java/com/oya/kr/commutiny/domain/CommunityView.java
  src/main/java/com/oya/kr/commutiny/domain/Vote.java
  src/main/java/com/oya/kr/commutiny/domain/VoteCheck.java
  src/main/java/com/oya/kr/global/domain/Base.java
  src/main/java/com/oya/kr/popup/domain/Category.java
  src/main/java/com/oya/kr/popup/domain/EntranceStatus.java
  src/main/java/com/oya/kr/popup/domain/Plan.java
  src/main/java/com/oya/kr/popup/domain/Popup.java
  src/main/java/com/oya/kr/popup/domain/PopupAdvertisement.java
  src/main/java/com/oya/kr/popup/domain/PopupCollection.java
  src/main/java/com/oya/kr/popup/domain/PopupView.java
  src/main/java/com/oya/kr/popup/domain/WithdrawalStatus.java
  src/main/java/com/oya/kr/user/domain/Gender.java
  src/main/java/com/oya/kr/user/domain/RegistrationType.java
  src/main/java/com/oya/kr/user/domain/Token.java
  src/main/java/com/oya/kr/user/domain/User.java
  src/main/java/com/oya/kr/user/domain/UserType.java
Labels: 🐥 feat

#3 [FEATURE] 어플리케이션 실행 시 팝업스토어 카테고리 저장 기능 구현
  pom.xml
  src/main/java/com/oya/kr/global/config/RootConfig.java
  src/main/java/com/oya/kr/global/domain/Base.java
  src/main/java/com/oya/kr/popup/config/InitializingCategoryConfig.java
  src/main/java/com/oya/kr/popup/domain/Category.java
  src/main/java/com/oya/kr/popup/mapper/CategoryMapper.java
  src/main/java/com/oya/kr/popup/mapper/dto/request/CategoryRequest.java
  src/main/java/com/oya/kr/popup/mapper/dto/response/CategoryResponse.java
  src/main/resources/com/oya/kr/popup/mapper/CategoryMapper.xml
  src/main/resources/mybatis/mybatis-config.xml
  src/test/java/com/oya/kr/common/SpringApplicationTest.java
  src/test/java/com/oya/kr/config/RootConfigTests.java
  src/test/java/com/oya/kr/popup/config/InitializingCategoryConfigTest.java
  src/test/java/com/oya/kr/popup/mapper/CategoryMapperTest.java
  src/test/java/com/oya/kr/test/mapper/TimeMapperTest.java
Labels: 🐥 feat

#5 [FEATURE] 현대백화점 지점 관련 리스트 조회 기능 구현
  src/main/java/com/oya/kr/global/config/WebConfig.java
  src/main/java/com/oya/kr/popup/controller/PlanController.java
  src/main/java/com/oya/kr/popup/controller/dto/response/DepartmentBranchResponse.java
  src/main/java/com/oya/kr/popup/controller/dto/response/DepartmentCategoryResponse.java
  src/main/java/com/oya/kr/popup/controller/dto/response/DepartmentFloorResponse.java
  src/main/java/com/oya/kr/popup/controller/dto/response/DepartmentFloorsWithCategoriesResponse.java
  src/main/java/com/oya/kr/popup/controller/dto/response/DepartmentResponse.java
  src/main/java/com/oya/kr/popup/controller/dto/response/DepartmentsResponse.java
  src/main/java/com/oya/kr/popup/domain/Category.java
  src/main/java/com/oya/kr/popup/domain/Department.java
  src/main/java/com/oya/kr/popup/domain/DepartmentBranch.java
  src/main/java/com/oya/kr/popup/domain/DepartmentFloor.java
  src/main/java/com/oya/kr/popup/service/PlanService.java
  src/test/java/com/oya/kr/config/jwt/TokenProviderTest.java
Labels: 🐥 feat

#6 [FEAT] 카카오 로그인 API 구현
  .gitignore
  src/main/java/com/oya/kr/global/config/RootConfig.java
  src/main/java/com/oya/kr/global/config/security/SecurityConfig.java
  src/main/java/com/oya/kr/global/config/security/TokenAuthenticationFilter.java
  src/main/java/com/oya/kr/global/domain/DateConvertor.java
  src/main/java/com/oya/kr/global/domain/Header.java
  src/main/java/com/oya/kr/global/jwt/JwtProperties.java
  src/main/java/com/oya/kr/user/controller/KaKaoController.java
  src/main/java/com/oya/kr/user/controller/client/KakaoApiClient.java
  src/main/java/com/oya/kr/user/controller/dto/request/AccessTokenRequest.java
  src/main/java/com/oya/kr/user/controller/dto/response/KakaoInfo.java
  src/main/java/com/oya/kr/user/domain/User.java
  src/main/java/com/oya/kr/user/domain/enums/Gender.java
  src/main/java/com/oya/kr/user/domain/enums/RegistrationType.java
  src/main/java/com/oya/kr/user/domain/enums/UserType.java
  src/main/java/com/oya/kr/user/mapper/UserMapper.java
  src/main/java/com/oya/kr/user/mapper/dto/request/SignupAdministratorMapperRequest.java
  src/main/java/com/oya/kr/user/mapper/dto/request/SignupBasicMapperRequest.java
  src/main/java/com/oya/kr/user/mapper/dto/response/UserMapperResponse.java
  src/main/java/com/oya/kr/user/service/KaKaoLoginService.java
  src/main/java/com/oya/kr/user/service/OAuthService.java
  src/main/java/com/oya/kr/user/service/UserService.java
  src/main/resources/com/oya/kr/user/mapper/UserMapper.xml
  src/main/resources/mybatis/mybatis-config.xml
  src/test/java/com/oya/kr/user/mapper/UserMapperTest.java
  src/test/java/com/oya/kr/user/service/KaKaoLoginServiceTest.java
  src/test/java/com/oya/kr/user/service/UserServiceTest.java
Labels: 🐥 feat

#7 [FEATURE] 사업계획서 관련 기능 구현
  pom.xml
  src/main/java/com/oya/kr/community/domain/Community.java
  src/main/java/com/oya/kr/community/domain/CommunityAdvertisement.java
  src/main/java/com/oya/kr/community/domain/CommunityReport.java
  src/main/java/com/oya/kr/community/domain/CommunityType.java
  src/main/java/com/oya/kr/community/domain/CommunityView.java
  src/main/java/com/oya/kr/community/domain/Vote.java
  src/main/java/com/oya/kr/community/domain/VoteCheck.java
  src/main/java/com/oya/kr/global/config/RootConfig.java
  src/main/java/com/oya/kr/global/config/WebConfig.java
  src/main/java/com/oya/kr/global/domain/Base.java
  src/main/java/com/oya/kr/global/domain/RegexValidator.java
  src/main/java/com/oya/kr/global/exception/GlobalErrorCodeList.java
  src/main/java/com/oya/kr/global/support/S3Connector.java
  src/main/java/com/oya/kr/global/support/S3Generator.java
  src/main/java/com/oya/kr/global/support/S3Provider.java
  src/main/java/com/oya/kr/global/support/StorageConnector.java
  src/main/java/com/oya/kr/global/support/StorageGenerator.java
  src/main/java/com/oya/kr/global/support/StorageProvider.java
  src/main/java/com/oya/kr/popup/controller/PlanController.java
  src/main/java/com/oya/kr/popup/controller/dto/request/PlanSaveRequest.java
  src/main/java/com/oya/kr/popup/domain/Category.java
  src/main/java/com/oya/kr/popup/domain/DepartmentBranch.java
  src/main/java/com/oya/kr/popup/domain/DepartmentFloor.java
  src/main/java/com/oya/kr/popup/domain/EntranceStatus.java
  src/main/java/com/oya/kr/popup/domain/Plan.java
  src/main/java/com/oya/kr/popup/domain/Popup.java
  src/main/java/com/oya/kr/popup/domain/PopupAdvertisement.java
  src/main/java/com/oya/kr/popup/domain/PopupCollection.java
  src/main/java/com/oya/kr/popup/domain/PopupView.java
  src/main/java/com/oya/kr/popup/exception/PlanErrorCodeList.java
  src/main/java/com/oya/kr/popup/mapper/PlanMapper.java
  src/main/java/com/oya/kr/popup/mapper/dto/request/PlanSaveMapperRequest.java
  src/main/java/com/oya/kr/popup/mapper/dto/request/PlanUpdateEntranceStatusMapperRequest.java
  src/main/java/com/oya/kr/popup/mapper/dto/response/PlanResponse.java
  src/main/java/com/oya/kr/popup/service/PlanService.java
  src/main/java/com/oya/kr/user/controller/client/KakaoApiClient.java
  src/main/java/com/oya/kr/user/domain/Business.java
  src/main/java/com/oya/kr/user/domain/RefreshToken.java
  src/main/java/com/oya/kr/user/domain/Token.java
  src/main/java/com/oya/kr/user/domain/User.java
  src/main/java/com/oya/kr/user/domain/enums/UserType.java
  src/main/java/com/oya/kr/user/exception/UserErrorCodeList.java
  src/main/java/com/oya/kr/user/mapper/BusinessMapper.java
  src/main/java/com/oya/kr/user/mapper/UserMapper.java
  src/main/resources/com/oya/kr/popup/mapper/PlanMapper.xml
  src/main/resources/com/oya/kr/user/mapper/BusinessMapper.xml
  src/main/resources/com/oya/kr/user/mapper/UserMapper.xml
  src/main/resources/mybatis/mybatis-config.xml
  src/test/java/com/oya/kr/config/jwt/TokenProviderTest.java
  src/test/java/com/oya/kr/popup/mapper/PlanMapperTest.java
Labels: 🐥 feat

#8 [FEATURE] 커뮤니티 create, read API 구현
  src/main/java/com/oya/kr/community/controller/CommunityController.java
  src/main/java/com/oya/kr/community/controller/VoteController.java
  src/main/java/com/oya/kr/community/controller/dto/request/CommunityRequest.java
  src/main/java/com/oya/kr/community/controller/dto/response/CommunityDetailResponse.java
  src/main/java/com/oya/kr/community/controller/dto/response/CommunityResponse.java
  src/main/java/com/oya/kr/community/controller/dto/response/VoteResponse.java
  src/main/java/com/oya/kr/community/domain/Community.java
  src/main/java/com/oya/kr/community/domain/CommunityImage.java
  src/main/java/com/oya/kr/community/domain/CommunityType.java
  src/main/java/com/oya/kr/community/exception/CommunityErrorCodeList.java
  src/main/java/com/oya/kr/community/mapper/CommunityMapper.java
  src/main/java/com/oya/kr/community/mapper/VoteMapper.java
  src/main/java/com/oya/kr/community/mapper/dto/request/ReadCommunityMapperRequest.java
  src/main/java/com/oya/kr/community/mapper/dto/request/SaveBasicMapperRequest.java
  src/main/java/com/oya/kr/community/mapper/dto/request/SaveVoteMapperRequest.java
  src/main/java/com/oya/kr/community/mapper/dto/request/VoteCheckMapperRequest.java
  src/main/java/com/oya/kr/community/mapper/dto/response/CommunityBasicMapperResponse.java
  src/main/java/com/oya/kr/community/service/CommunityService.java
  src/main/java/com/oya/kr/community/service/VoteService.java
  src/main/java/com/oya/kr/global/config/RootConfig.java
  src/main/java/com/oya/kr/global/config/security/SecurityConfig.java
  src/main/java/com/oya/kr/global/dto/Pagination.java
  src/main/java/com/oya/kr/popup/domain/Category.java
  src/main/java/com/oya/kr/user/domain/enums/UserType.java
  src/main/java/com/oya/kr/user/mapper/UserMapper.java
  src/main/java/com/oya/kr/user/mapper/dto/response/UserMapperResponse.java
  src/main/resources/com/oya/kr/community/mapper/CommunityMapper.xml
  src/main/resources/com/oya/kr/community/mapper/VoteMapper.xml
  src/main/resources/com/oya/kr/user/mapper/UserMapper.xml
  src/main/resources/mybatis/mybatis-config.xml
  src/test/java/com/oya/kr/commutiny/mapper/CommunityMapperTest.java
  src/test/java/com/oya/kr/commutiny/mapper/VoteMapperTest.java
  src/test/java/com/oya/kr/user/mapper/UserMapperTest.java
Labels: 🐥 feat

#11 [FEATURE] Repository 계층 추가
  src/main/java/com/oya/kr/community/repository/CommunityRepository.java
  src/main/java/com/oya/kr/community/repository/VoteRepository.java
  src/main/java/com/oya/kr/community/service/CommunityService.java
  src/main/java/com/oya/kr/community/service/VoteService.java
  src/main/java/com/oya/kr/global/support/S3Connector.java
  src/main/java/com/oya/kr/global/support/StorageConnector.java
  src/main/java/com/oya/kr/popup/config/InitializingCategoryConfig.java
  src/main/java/com/oya/kr/popup/domain/enums/PopupSort.java
  src/main/java/com/oya/kr/popup/repository/CategoryRepository.java
  src/main/java/com/oya/kr/popup/repository/PlanRepository.java
  src/main/java/com/oya/kr/popup/repository/PopupRepository.java
  src/main/java/com/oya/kr/popup/service/PlanService.java
  src/main/java/com/oya/kr/popup/service/PopupService.java
  src/main/java/com/oya/kr/user/repository/UserRepository.java
  src/main/java/com/oya/kr/user/service/KaKaoLoginService.java
  src/main/java/com/oya/kr/user/service/UserService.java
Labels: 🐥 feat

#12 [REFACTOR] profile 설정 및 Github Actions 적용
  .github/workflows/gradle.yml
  .gitignore
  Dockerfile
  pom.xml
  src/main/java/com/oya/kr/global/config/RootConfig.java
Labels: ⚙️ chore, ⭐️ refactor

#14 [FIX] 사업계획서 및 팝업스토어 관련 에러 처리
  src/main/java/com/oya/kr/popup/repository/PopupRepository.java
  src/main/java/com/oya/kr/popup/service/PopupService.java
  src/main/resources/com/oya/kr/popup/mapper/PlanMapper.xml
Labels: 🛠️ bug

#18 [FIX] 백엔드 api 수정 및 예외 추가
  src/main/java/com/oya/kr/community/service/CommunityService.java
  src/main/java/com/oya/kr/global/config/WebCorsConfig.java
  src/main/java/com/oya/kr/global/config/security/SecurityConfig.java
  src/main/java/com/oya/kr/global/config/security/TokenAuthenticationFilter.java
  src/main/java/com/oya/kr/global/jwt/TokenProvider.java
  src/main/java/com/oya/kr/user/controller/KaKaoController.java
  src/main/java/com/oya/kr/user/controller/UserController.java
  src/main/java/com/oya/kr/user/controller/dto/response/BusinessUserResponse.java
  src/main/java/com/oya/kr/user/mapper/dto/response/BusinessMapperResponse.java
  src/main/resources/com/oya/kr/user/mapper/UserMapper.xml
Labels: 🛠️ bug, ⚙️ chore, 🐥 feat

#22 [REFACTOR] 팝업스토어, 커뮤니티 게시글에 스크랩 여부 및 작성 여부 추가
  src/main/java/com/oya/kr/community/controller/dto/response/CommunityDetailResponse.java
  src/main/java/com/oya/kr/community/mapper/CommunityMapper.java
  src/main/java/com/oya/kr/community/repository/CommunityRepository.java
  src/main/java/com/oya/kr/community/service/CommunityService.java
  src/main/java/com/oya/kr/popup/controller/dto/response/PopupResponse.java
  src/main/java/com/oya/kr/popup/mapper/PopupMapper.java
  src/main/java/com/oya/kr/popup/mapper/dto/request/PopupDetailMapperRequest.java
  src/main/java/com/oya/kr/popup/mapper/dto/response/PopupDetailMapperResponse.java
  src/main/java/com/oya/kr/popup/repository/PopupRepository.java
  src/main/java/com/oya/kr/popup/service/PopupService.java
  src/main/resources/com/oya/kr/community/mapper/CommunityMapper.xml
  src/main/resources/com/oya/kr/popup/mapper/PopupMapper.xml
  src/main/resources/mybatis/mybatis-config.xml
  src/test/java/com/oya/kr/community/mapper/CommunityMapperTest.java
  src/test/java/com/oya/kr/popup/mapper/PlanMapperTest.java
  src/test/java/com/oya/kr/popup/mapper/PopupMapperTest.java
Labels: ⭐️ refactor
